
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FacadeImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9191/annuaire?wsdl")
public class FacadeImplService
    extends Service
{

    private final static URL FACADEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FACADEIMPLSERVICE_EXCEPTION;
    private final static QName FACADEIMPLSERVICE_QNAME = new QName("http://service/", "FacadeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/annuaire?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACADEIMPLSERVICE_WSDL_LOCATION = url;
        FACADEIMPLSERVICE_EXCEPTION = e;
    }

    public FacadeImplService() {
        super(__getWsdlLocation(), FACADEIMPLSERVICE_QNAME);
    }

    public FacadeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACADEIMPLSERVICE_QNAME, features);
    }

    public FacadeImplService(URL wsdlLocation) {
        super(wsdlLocation, FACADEIMPLSERVICE_QNAME);
    }

    public FacadeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACADEIMPLSERVICE_QNAME, features);
    }

    public FacadeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacadeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FacadeImpl
     */
    @WebEndpoint(name = "FacadeImplPort")
    public FacadeImpl getFacadeImplPort() {
        return super.getPort(new QName("http://service/", "FacadeImplPort"), FacadeImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacadeImpl
     */
    @WebEndpoint(name = "FacadeImplPort")
    public FacadeImpl getFacadeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "FacadeImplPort"), FacadeImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACADEIMPLSERVICE_EXCEPTION!= null) {
            throw FACADEIMPLSERVICE_EXCEPTION;
        }
        return FACADEIMPLSERVICE_WSDL_LOCATION;
    }

}
